### ISSUE TITLE
Replace pyqtgraph with custom widget

### ISSUE THREAD

**Issue by frmdstryr** [codelv/inkcut#105]
pyqtgraph was used for simplicity but since all drawing is done with a QPainterPath, pyqtgraph and numpy can be removed.

**Comment by frmdstryr** [comment]
For anyone that want's to try it, I just rebased this from a long time ago..
see https://github.com/inkcut/inkcut/tree/new-viewer

**Comment by aaujon** [comment]
Hi, I give it a try, it works well, just 2 things : 
- when starting inkcut, the image is displayed too high, see screenshot  : 
![Capture d’écran de 2020-05-25 13-34-45](https://user-images.githubusercontent.com/1658471/82809563-afc8bd80-9e8c-11ea-99b3-9ffc69243636.png)
- Sometimes, when moving the image (not sure how to reproduce it, just have to play with zoom and move) it crashes with : 
`2020-05-25 13:39:38,289 | DEBUG   | inkcut | Starting plugin 'inkcut.ui'
2020-05-25 13:39:38,290 | WARNING | inkcut | Plugin inkcut.ui state restored from: /home/iloarnaud/.config/inkcut/inkcut.ui.json
Traceback (most recent call last):
  File "/home/iloarnaud/.local/lib/python3.8/site-packages/enamlx/qt/qt_graphics_view.py", line 669, in mouseMoveEvent
  File "/home/iloarnaud/git/inkcut/inkcut/preview/view.enaml", line 59, in mouse_move_event
  File "/home/iloarnaud/.local/lib/python3.8/site-packages/enamlx/widgets/graphics_view.py", line 52, in __init__
NameError: name 'super' is not defined
`

**Comment by aaujon** [comment]
Other stack when it crashes : 
2020-05-25 13:40:34,924 | WARNING | inkcut | Plugin inkcut.ui state restored from: /home/iloarnaud/.config/inkcut/inkcut.ui.json
Traceback (most recent call last):
  File "/home/iloarnaud/.local/lib/python3.8/site-packages/enamlx/qt/qt_graphics_view.py", line 663, in mousePressEvent
NameError: name 'super' is not defined
Traceback (most recent call last):
  File "/home/iloarnaud/.local/lib/python3.8/site-packages/enamlx/qt/qt_graphics_view.py", line 669, in mouseMoveEvent
  File "/home/iloarnaud/git/inkcut/inkcut/preview/view.enaml", line 59, in mouse_move_event
  File "/home/iloarnaud/.local/lib/python3.8/site-packages/enamlx/widgets/graphics_view.py", line 52, in __init__
TypeError: super() is not allowed in a declarative function,  use SomeClass.some_method(self, ...) instead.
Unhandled Python exception

**Comment by frmdstryr** [comment]
Thanks for giving it a try! I think the errors above are related to #245 (seems like a problem with recent versions of enaml).

What are your thoughts on missing the x & y gridlines? Do you think those are those necessary?

**Comment by aaujon** [comment]
The issue is different, but can be, I will try to downgrade it.
I  personally don't use the gridlines and I don't think they can be usefull in any workflow.

**Comment by aaujon** [comment]
Ok the crash are caused by python 3.8/enaml 0.11/atom0.6, it's working great with python 3.7/enaml 0.10.4/atom0.4.2
