### ISSUE TITLE
Inkscape plugin Mac 

### ISSUE THREAD

**Issue by AntonioAmico** [codelv/inkcut#155]
Hi, I am getting the following error when I'm trying to lunch "Cut selection" from Inkscape on MacOs 10.14.3:

Traceback (most recent call last):
 File "inkcut_cut.py", line 73, in <module>
  effect.affect()
 File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 283, in affect
  self.effect()
 File "inkcut_cut.py", line 68, in effect
  p.stdin.write(inkex.etree.tostring(document))
IOError: [Errno 32] Broken pipe

the log file say:
2019-04-26 08:53:30,279 | ERROR   | inkcut | Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/inkcut/app.py", line 73, in main
    from inkcut.core.workbench import InkcutWorkbench
  File "/usr/local/lib/python3.7/site-packages/inkcut/core/workbench.py", line 22, in <module>
    from inkcut.core.utils import log
  File "/usr/local/lib/python3.7/site-packages/inkcut/core/utils.py", line 21, in <module>
    from .svg import QtSvgDoc
  File "/usr/local/lib/python3.7/site-packages/inkcut/core/svg.py", line 20, in <module>
    from lxml import etree
ImportError: dlopen(/Applications/Inkscape.app/Contents/Resources/lib/python2.7/site-packages/lxml/etree.so, 2): Symbol not found: _PyBaseString_Type
  Referenced from: /Applications/Inkscape.app/Contents/Resources/lib/python2.7/site-packages/lxml/etree.so
  Expected in: flat namespace
 in /Applications/Inkscape.app/Contents/Resources/lib/python2.7/site-packages/lxml/etree.so

Can you help me?
<img width="717" alt="Schermata 2019-04-26 alle 09 01 35" src="https://user-images.githubusercontent.com/50010154/56789383-05eaad80-6802-11e9-9583-47fba5c3ff69.png">

**Comment by frmdstryr** [comment]
Does `inkcut` start if you launch it from a terminal window?

**Comment by AntonioAmico** [comment]
Yes, it starts, I can plot one time, then inkcut stops working and the Mac need to reboot

**Comment by frmdstryr** [comment]
Thanks. Can you provide some more information...

What device are you using? How is it connected?

When Inkcut "stops working",  what does that mean? It locks up? Exits and doesn't start? Gives an error? etc...

Can you attach logs "Help -> Logs"?

**Comment by frmdstryr** [comment]
Please reopen if needed.
